### ISSUE TITLE
Examples for "stream" command are non sequitur

### ISSUE THREAD

**Issue by csylvain** [flexradio/smartsdr-api-docs#2]
the examples given for the "stream" command are, in fact, an examples of a "ping" command and therefore unhelpful.

see
`https://github.com/flexradio/smartsdr-api-docs/wiki/TCPIP-stream`

granted, someone probably threw placeholder text as an example. but even one proofreading pass should have prompted an update.

**Comment by ke5dto** [comment]
We updated the page.  Please take another look and let us know if makes more sense to you now.

**Comment by csylvain** [comment]
oh, yes, that is much better! thanks are in order.
the type "dax_mic" is particularly intriguing .. not sure if i have that in my list of strings scraped from the firmware image.
